version: "3.8"

services:
  web:
    image: craftcms/nginx:7.4-dev
    depends_on:
      - "mysql"
    ports:
      - "8081:8080"
    env_file: ./app/.env
    environment:
      PHP_MEMORY_LIMIT: 512M
      PHP_POST_MAX_SIZE: 25M
      XDEBUG_CONFIG: client_host=host.docker.internal
    volumes:
      - ./app:/app:cached

  console:
    image: craftcms/cli:7.4
    volumes:
      - ./app:/app:cached
    depends_on:
      - "mysql"
      - "web"
    env_file: ./app/.env
    command: ["./craft", "queue/listen"]

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vitecraft
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql:delegated

  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  db_data:
